version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: nc1
    ports:
      - "80:80"
    depends_on:
      - wsgi

  wsgi:
    build:
      context: ./
      dockerfile: server/Dockerfile
    container_name: fast_api
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    container_name: postgres_container


volumes:
  db_volume:
    name: pg_volume_1
