version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=bigbox9
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=emais_kokkinn_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: